export const APARTAMENT_CHANGE = 'APARTAMENT_CHANGE';
export const RESIDENTIAL_CHANGE = 'RESIDENTIAL_CHANGE';
export const ASSEMBLY_CHANGE = 'ASSEMBLY_CHANGE';
export const PARTICIPANTS_CHANGE = 'PARTICIPANTS_CHANGE';
export const QUORUM_CHANGE = 'QUORUM_CHANGE';
export const APARTAMENTS_CHANGE = 'APARTAMENTS_CHANGE';